---
- name: Expected to fail
  hosts: all
  sources:
    - alex_izquierdo.eda_testing.eda_failer:
        iterations: 5
        fail_at_index: 3
        delay: 1
  rules:
    - name: Expected to fail at index 3
      condition: event.i is defined
      action:
        debug:
          msg: "Event received: #{{ event.i }}"
